# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sealsmodel
  version: "2.1.1"

package:
  name: "${{ name|lower }}"
  version: "${{ version }}"

source:
  url: https://files.pythonhosted.org/packages/fb/72/09839b3825cf243153c0d72c94d93f48a35b5778254bcf7767cbdd08134b/sealsmodel-${{ version }}.tar.gz
  sha256: 12d50d93a79d12d33d7301d8f050f56bb989c5025ecda1eca3331cdc123f20e4

build:
  skip:
    - match(python, ">=3.12")
  script: |
    # Force re-cythonization by deleting any existing cython files.
    # Re-cythonization needed because of varying numpy ABIs in conda-forge matrix.
    {{ PYTHON }} -c "import os; from pathlib import Path; [f.unlink() for f in Path(os.environ['SRC_DIR']).rglob('*.cpp')]"
    python -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - cython
        - numpy
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools >=74.1
    - wheel
    - cython >3.0.0
    - setuptools_scm >=8.0.0
    - numpy
    - pip
  run:
    - python
    - geopandas
    - google-cloud-storage
    - hazelbean
    - matplotlib-base
    - netcdf4
    - gdal
    - pandas
    - pygeoprocessing
    - scipy <1.16.0
    - pytest # until hazelbean's conda-forge config requires it
    - pytest-cov # until hazelbean's conda-forge config requires it
    - pytest-benchmark <5.3 # until hazelbean's conda-forge config requires it.  v5.3 introduced dependency on py-cpuinfo2, which is not on conda-forge, which fails pip-check.
    # A version incompatibility with rioxarray/xarray was causing a build failure on pip check.
    - xarray >=2024.7.0
    - rioxarray >=0.18.1

tests:
  # Uncomment once there are tests to run
  #- script:
  #    - pytest
  #  requirements:
  #    run:
  #      - pytest
  #      - pytest-cov
  #      - pytest-benchmark

  - python:
      imports:
        - seals
        - seals.seals_cython_functions
        - hazelbean
      pip_check: true
    requirements:
      run:
        - pytest
        - pytest-cov
        - pytest-benchmark

about:
  homepage: https://github.com/jandrewjohnson/seals_dev
  summary: Land-use change model and downscaler
  license: LicenseRef-LICENSE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phargogh
    - jandrewjohnson
    - chiacsen
